# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Install Dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    #- name: Test
    #  run: go test -v ./...

    #- name: Lint Code
    #  uses: golangci/golangci-lint-action@v3
    #  with:
    #    version: latest
    #    args: "--timeout 5m"

    #- name: Security Check
    #  run: go install github.com/securego/gosec/v2/cmd/gosec@latest && gosec ./...

    #- name: Check Code Coverage
    #  run: |
    #    go test -coverprofile=coverage.out ./...
    #    go tool cover -func=coverage.out

